### ISSUE TITLE
Support pagination for multilanguage services

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#1]
The webapp need to have pagination for multilanguage projects, pages and text containers. Creating the issue to track pagination for the following

- Projects
- Pages
- Text Containers (Values, Paragraphs, NameValues, ContainerizedNameValues, ContainerizedValues)

**Comment by perpetualintelligence** [comment]
Acknowledged, added to release plans for May-2020.

**Comment by perpetualintelligence** [comment]
Pagination added for Web App for multilanguage projects and pages. Texts are stored in Json files so that are not paged...
