### ISSUE TITLE
Manual Translation forces to enter translation for all languages

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#23]
If i create a text holder with Manual Translation,  i am forced to add translation for all the languages defined in the owning page. This should not be enforced.

For manual translation workflow as a user i would like to add source text and then let my translation provider add text for respective languages.

**Comment by perpetualintelligence** [comment]
Thanks for reporting the issue, enhancement added to v1-apr milestone.

**Comment by perpetualintelligence** [comment]
Added the feature in v1.

Manual translation now does not force user to enter the translations for all the text upfront. User can selectively add translations for respective languages during create and edit them later as well.
