### ISSUE TITLE
Support multile translation units in a page

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#25]
As per documentation currently the translation page supports individual translation units (values, words paragraphs, properties etc...)

We would like the translation page support multiple translation units (for e.g. mixed or a combination of translation units in the same page.

This is helpful in having all the multilingual data  in the application content in the same page.

**Comment by perpetualintelligence** [comment]
@ameyasubhedar thanks for reporting the enhancement. Currently, you can create multiple pages each with separate translation unit type. Mixed translation units are currently not supported.

We have added this to our enhancement plan...

**Comment by perpetualintelligence** [comment]
API and Web-app enhanced to support multiple translation units in a page. You can now create a page with **Mixed** translation unit type. Documentation needs to be updated [#26 ](https://github.com/perpetualintelligence/pidotapp-bugs/issues/26)

![image](https://user-images.githubusercontent.com/62374075/81611797-8d18ae00-9390-11ea-9ed8-4f4dffe98f58.png)
