### ISSUE TITLE
Need a way for define terminologies for each project.

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#27]
Once we define the custom terminology we are not able to assign it to the project.

Multiple customer may define different terminologies. 

Need a way to distinguish the customer specific terminologies.

**Comment by perpetualintelligence** [comment]
@ameyasubhedar your enhancement request is available for beta in **v1/multilanguage/projects** API. You can now define terminology file for each project. Please note that you can define upto 256 terms in hosted terminology file. If you are using enterprise integration with your AWS then your terminology file will be validated by AWS Custom terminology service.
