### ISSUE TITLE
Multilanguage page does not lock

### ISSUE THREAD

**Issue by VedantSahadeo** [perpetualintelligence/pidotapp-bugs#28]
When I try to lock the page I get an error message that it is already locked, but its not because I can create and modify translation unit in it.

![image](https://user-images.githubusercontent.com/62402148/81526908-cd831800-930d-11ea-8d14-7fd944e3862a.png)

Below is the error message...
![image](https://user-images.githubusercontent.com/62402148/81526947-ec81aa00-930d-11ea-99ad-a9d801706704.png)

**Comment by perpetualintelligence** [comment]
@VedantSahadeo thanks for reporting the issue with lock service for pages. We will revert back asap... Adding **high priority** flag.

**Comment by perpetualintelligence** [comment]
Update... dev  team identified the issue, working on the fix for v1-may-2020

**Comment by perpetualintelligence** [comment]
Fixed in v1/multilanguage/pages API and WebApp...
