### ISSUE TITLE
Translation unit cannot be deleted in a mixed page.

### ISSUE THREAD

**Issue by VedantSahadeo** [perpetualintelligence/pidotapp-bugs#29]
I am not able to delete any translation units (values, paragraphs, properties, etc.)in a mixed page. I can edit or create them successfully but delete  is a problem.
![image](https://user-images.githubusercontent.com/62402148/81527687-cb21bd80-930f-11ea-956e-7d2b5ccae76e.png)

**Comment by perpetualintelligence** [comment]
@VedantSahadeo thanks for reporting the issue with lock service for pages. We will revert back asap... Adding high priority flag.

**Comment by perpetualintelligence** [comment]
Fixed in **v1/multilanguage/{translationunit}** API and web app.
