### ISSUE TITLE
Provide lock unlock UI for multilanguage pages

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#3]
multilanguages pages have lock unlock APIs but the perpetualintelligence.com web app does not provide a way to lock, unlock pages manually.

![image](https://user-images.githubusercontent.com/13166236/77223781-d8df7180-6b1c-11ea-9ee7-bd053d3453b1.png)

What is the plan to provide lock, unlock for pages from web app as well

**Comment by perpetualintelligence** [comment]
Lock Unlock UI menus are available on multilangauge pages.

![image](https://user-images.githubusercontent.com/62374075/78843065-99d36c00-79b6-11ea-9fa2-6600d48c903d.png)
