### ISSUE TITLE
Manual Translation checkbox not selected but Target Language fields still visible on the Page 'Values' form

### ISSUE THREAD

**Issue by nehadgautam** [perpetualintelligence/pidotapp-bugs#39]
On a 'Mixed' type Page with 'Hosted Translation' selected, try to add any Translation unit - 'Values', 'Paragraph', 'Property' etc. On the Create form, it can be observed that the 'Manual Translation' option is initially unchecked but Target Language fields are visible on the Page. Target Language fields should only be visible and available for editing when 'Manual Translation' option is checked.

![image](https://user-images.githubusercontent.com/65241627/81955885-45ac4f00-9628-11ea-9a4e-0cc51db89824.png)

**Comment by perpetualintelligence** [comment]
@nehadgautam thanks for reporting the issue. We have added this to our enhancement list for May-2020 v1 release.

**Comment by perpetualintelligence** [comment]
Fixed in v1.
