### ISSUE TITLE
pi.multilanguage(); creates folder structure for AWS integration

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#4]
Why does the multilangauge service creates additional folders once the ARN for AWS S3 container is specified ?

Currently it creates 
AWS S3 ->  guid -> multilangauge -> projectid -> pageId

Expectation is
AWS S3 -> projectid -> pageid

**Comment by perpetualintelligence** [comment]
Thanks for reporting the issue... the code was creating the AWS directory structure {businessAccountId}/{application}/{projectId}/{pageId} 

Changed the functionality to now created the project directories directly, under the AWS S3
AWSS3ARN / {projectId}/{pageId}
