### ISSUE TITLE
Page create Modal form does not show for Manual Translations

### ISSUE THREAD

**Issue by ameyasubhedar** [perpetualintelligence/pidotapp-bugs#7]
I created a project with Manual translation and AWS S3 storage. After that I cannot create the page anymore.

I can create the Page for AWS translate and AWS S3 storage. I did not check the API.

**Comment by perpetualintelligence** [comment]
Thanks for reporting the issues.

This is an underlying bug in the multilangugage API as well as the web app.

**Comment by perpetualintelligence** [comment]
Identified 2 issues:
- The langauges API on /vi/multilangauge/projects is failing for Manual translation provider
- /vi/multilangauge/projects/{texts} are failing for Manual translation, works well for automatic.

**Comment by perpetualintelligence** [comment]
API and Web app fixed in v1/multilangauge API
